
root: /about

Home: /about
Archives: /archives
About: /about

language: en

author: devtty1er
description:

disqus:
  enable: false
  shortname:

google_site_verification:
google_analytics: UA-127405375-1
